#!/bin/bash


## Prep
rm -rf temp
mkdir temp
mkdir temp/podcasts-with-entities

# Download Python packages
pip3 install -U pip setuptools wheel
pip3 install -U spacy
python3 -m spacy download en_core_web_sm

# Get the latest files from podcast data generator
ORG_NAME=podcast-data-lab
REPO_NAME=podcast-data-generator
LATEST_VERSION=$(curl -s https://api.github.com/repos/${ORG_NAME}/${REPO_NAME}/releases/latest | grep "tag_name" | cut -d'v' -f2 | cut -d'"' -f1)

wget -P temp "https://github.com/lbugasu/podcast-data-generator/archive/refs/tags/v${LATEST_VERSION}.zip"
unzip "temp/v${LATEST_VERSION}.zip" -d temp

python3 nex.py ${LATEST_VERSION}

## Finalize
mkdir dist

cp -R temp/podcasts-with-entities dist/
cp -R .github dist/
cp license.txt dist/license